// <auto-generated />
using System;
using System.Collections.Generic;
using LastMileUY.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LastMileUY.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LastMileUY.API.Modules.Comercios.Domain.Comercio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("RUT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RUT")
                        .IsUnique();

                    b.ToTable("Comercios", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Comercios.Domain.OperadorComercio", b =>
                {
                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaVinculacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperadorId", "ComercioId");

                    b.HasIndex("ComercioId");

                    b.ToTable("OperadoresComercios", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Destinatarios.Domain.Destinatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Destinatarios", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Destinatarios.Domain.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Apartamento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("DestinatarioId");

                    b.ToTable("Direcciones", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.Devolucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId")
                        .IsUnique();

                    b.ToTable("Devoluciones", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.IntentoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MotivoNoEntregaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroIntento")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ParadaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MotivoNoEntregaId");

                    b.HasIndex("ParadaId");

                    b.HasIndex("EnvioId", "NumeroIntento")
                        .IsUnique();

                    b.ToTable("IntentosEntrega", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.MotivoNoEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "Nombre")
                        .IsUnique();

                    b.ToTable("MotivosNoEntrega", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.PruebaEntrega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentoReceptor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaHoraDispositivo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaArchivoKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FotoArchivoKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IntentoEntregaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("NombreReceptor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("IntentoEntregaId")
                        .IsUnique();

                    b.ToTable("PruebasEntrega", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Envios.Domain.Bulto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AltoCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("AnchoCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("LargoCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId", "Codigo")
                        .IsUnique();

                    b.ToTable("Bultos", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Envios.Domain.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoSeguimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostoEnvio")
                        .HasColumnType("numeric");

                    b.Property<int?>("CuadroTarifarioId")
                        .HasColumnType("integer");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("integer");

                    b.Property<int>("DireccionId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FranjaHorariaId")
                        .HasColumnType("integer");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenciaExterna")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DireccionEntrega", "LastMileUY.API.Modules.Envios.Domain.Envio.DireccionEntrega#DireccionEntrega", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Apartamento")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("CodigoPostal")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Departamento")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Referencia")
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CodigoSeguimiento")
                        .IsUnique();

                    b.HasIndex("ComercioId");

                    b.HasIndex("CuadroTarifarioId");

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("DireccionId");

                    b.HasIndex("FranjaHorariaId");

                    b.HasIndex("OperadorId");

                    b.ToTable("Envios", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Identidad.Domain.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Identidad.Domain.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OperadorId");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Ambito", "\"OperadorId\" IS NULL OR \"ComercioId\" IS NULL");
                        });
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Notificaciones.Domain.EntregaAviso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadIntentos")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaProximoIntento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaUltimoIntento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SuscripcionAvisosId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("EventoId")
                        .IsUnique();

                    b.HasIndex("SuscripcionAvisosId");

                    b.HasIndex("Estado", "FechaProximoIntento");

                    b.ToTable("EntregasAvisos", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Notificaciones.Domain.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId", "FechaCreacion");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Notificaciones.Domain.SuscripcionAvisos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UrlDestino")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("OperadorId", "ComercioId", "TipoEvento", "Activa");

                    b.ToTable("SuscripcionesAvisos", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.FranjaHoraria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId", "Nombre")
                        .IsUnique();

                    b.ToTable("FranjasHorarias", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("Operadores", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.ReglaOperativa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HorasEntreIntentos")
                        .HasColumnType("integer");

                    b.Property<int>("HorasParaIniciarDevolucion")
                        .HasColumnType("integer");

                    b.Property<int>("MaximoIntentosEntrega")
                        .HasColumnType("integer");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<int>("PlazoEntregaHoras")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereDocumentoReceptor")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereFirma")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiereFotografia")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "Modalidad")
                        .IsUnique()
                        .HasFilter("\"Activa\" = true");

                    b.ToTable("ReglasOperativas", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.Zona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "Nombre")
                        .IsUnique();

                    b.ToTable("Zonas", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Incidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObservacionesResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("Resuelta")
                        .HasColumnType("boolean");

                    b.Property<int>("RutaId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("RutaId", "FechaHora");

                    b.ToTable("Incidencias", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Parada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaLlegada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("RutaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("RutaId", "Orden")
                        .IsUnique();

                    b.ToTable("Paradas", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Posicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<int>("RutaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutaId", "FechaHora");

                    b.ToTable("Posiciones", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Rendicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadEntregados")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadNoEntregados")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RutaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RutaId")
                        .IsUnique();

                    b.ToTable("Rendiciones", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Repartidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicenciaConducir")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Repartidores", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Ruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<int>("RepartidorId")
                        .HasColumnType("integer");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Rutas", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CapacidadPesoKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("CapacidadVolumenM3")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "Matricula")
                        .IsUnique();

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Seguimiento.Domain.EventoEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPublico")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("Longitud")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponsableId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId", "FechaHora");

                    b.ToTable("EventosEnvio", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.AjusteTarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("TarifaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TarifaId");

                    b.ToTable("AjustesTarifa", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.CuadroTarifario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VigenciaDesde")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId", "Version")
                        .IsUnique();

                    b.ToTable("CuadrosTarifarios", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.DetalleLiquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EnvioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Importe")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("LiquidacionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("LiquidacionId", "EnvioId")
                        .IsUnique();

                    b.ToTable("DetallesLiquidacion", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.Liquidacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ComercioId")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ImporteTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodoDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodoHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ComercioId");

                    b.HasIndex("OperadorId", "ComercioId", "PeriodoDesde", "PeriodoHasta");

                    b.ToTable("Liquidaciones", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int>("CuadroTarifarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PesoMaximoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PesoMinimoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioPorKgAdicional")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VolumenMaximoM3")
                        .HasColumnType("numeric");

                    b.Property<decimal>("VolumenMinimoM3")
                        .HasColumnType("numeric");

                    b.Property<int>("ZonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CuadroTarifarioId");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Comercios.Domain.OperadorComercio", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Comercios.Domain.Comercio", null)
                        .WithMany()
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Destinatarios.Domain.Direccion", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Destinatarios.Domain.Destinatario", null)
                        .WithMany("Direcciones")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.Devolucion", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithOne("Devolucion")
                        .HasForeignKey("LastMileUY.API.Modules.Entregas.Domain.Devolucion", "EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.IntentoEntrega", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithMany("IntentosEntrega")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Entregas.Domain.MotivoNoEntrega", null)
                        .WithMany("IntentosEntrega")
                        .HasForeignKey("MotivoNoEntregaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LastMileUY.API.Modules.Rutas.Domain.Parada", null)
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.MotivoNoEntrega", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("MotivosNoEntrega")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.PruebaEntrega", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Entregas.Domain.IntentoEntrega", null)
                        .WithOne("PruebaEntrega")
                        .HasForeignKey("LastMileUY.API.Modules.Entregas.Domain.PruebaEntrega", "IntentoEntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Envios.Domain.Bulto", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithMany("Bultos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Envios.Domain.Envio", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Comercios.Domain.Comercio", null)
                        .WithMany("Envios")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Tarifas.Domain.CuadroTarifario", null)
                        .WithMany("Envios")
                        .HasForeignKey("CuadroTarifarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LastMileUY.API.Modules.Destinatarios.Domain.Destinatario", null)
                        .WithMany("Envios")
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Destinatarios.Domain.Direccion", null)
                        .WithMany("Envios")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.FranjaHoraria", null)
                        .WithMany("Envios")
                        .HasForeignKey("FranjaHorariaId");

                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("Envios")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Identidad.Domain.Usuario", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Comercios.Domain.Comercio", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Notificaciones.Domain.EntregaAviso", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithMany("EntregasAvisos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Notificaciones.Domain.SuscripcionAvisos", null)
                        .WithMany("EntregasAvisos")
                        .HasForeignKey("SuscripcionAvisosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Notificaciones.Domain.Notificacion", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithMany("Notificaciones")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Notificaciones.Domain.SuscripcionAvisos", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Comercios.Domain.Comercio", null)
                        .WithMany("SuscripcionesAvisos")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("SuscripcionesAvisos")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.FranjaHoraria", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Zona", null)
                        .WithMany("FranjasHorarias")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.ReglaOperativa", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("ReglasOperativas")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.Zona", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("Zonas")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Incidencia", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Rutas.Domain.Ruta", null)
                        .WithMany("Incidencias")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Parada", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithMany("Paradas")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Rutas.Domain.Ruta", null)
                        .WithMany("Paradas")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Posicion", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Rutas.Domain.Ruta", null)
                        .WithMany("Posiciones")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Rendicion", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Rutas.Domain.Ruta", null)
                        .WithOne("Rendicion")
                        .HasForeignKey("LastMileUY.API.Modules.Rutas.Domain.Rendicion", "RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Repartidor", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("Repartidores")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Identidad.Domain.Usuario", null)
                        .WithOne()
                        .HasForeignKey("LastMileUY.API.Modules.Rutas.Domain.Repartidor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Ruta", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("Rutas")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Rutas.Domain.Repartidor", null)
                        .WithMany("Rutas")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Rutas.Domain.Vehiculo", null)
                        .WithMany("Rutas")
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Vehiculo", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("Vehiculos")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Seguimiento.Domain.EventoEnvio", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithMany("Eventos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.AjusteTarifa", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Tarifas.Domain.Tarifa", null)
                        .WithMany("Ajustes")
                        .HasForeignKey("TarifaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.CuadroTarifario", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("CuadrosTarifarios")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.DetalleLiquidacion", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Envios.Domain.Envio", null)
                        .WithMany("DetallesLiquidacion")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Tarifas.Domain.Liquidacion", null)
                        .WithMany("Detalles")
                        .HasForeignKey("LiquidacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.Liquidacion", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Comercios.Domain.Comercio", null)
                        .WithMany("Liquidaciones")
                        .HasForeignKey("ComercioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Operadores.Domain.Operador", null)
                        .WithMany("Liquidaciones")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.Tarifa", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Tarifas.Domain.CuadroTarifario", null)
                        .WithMany("Tarifas")
                        .HasForeignKey("CuadroTarifarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Identidad.Domain.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Identidad.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Identidad.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Identidad.Domain.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LastMileUY.API.Modules.Identidad.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LastMileUY.API.Modules.Identidad.Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Comercios.Domain.Comercio", b =>
                {
                    b.Navigation("Envios");

                    b.Navigation("Liquidaciones");

                    b.Navigation("SuscripcionesAvisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Destinatarios.Domain.Destinatario", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Envios");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Destinatarios.Domain.Direccion", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.IntentoEntrega", b =>
                {
                    b.Navigation("PruebaEntrega");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Entregas.Domain.MotivoNoEntrega", b =>
                {
                    b.Navigation("IntentosEntrega");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Envios.Domain.Envio", b =>
                {
                    b.Navigation("Bultos");

                    b.Navigation("DetallesLiquidacion");

                    b.Navigation("Devolucion");

                    b.Navigation("EntregasAvisos");

                    b.Navigation("Eventos");

                    b.Navigation("IntentosEntrega");

                    b.Navigation("Notificaciones");

                    b.Navigation("Paradas");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Notificaciones.Domain.SuscripcionAvisos", b =>
                {
                    b.Navigation("EntregasAvisos");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.FranjaHoraria", b =>
                {
                    b.Navigation("Envios");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.Operador", b =>
                {
                    b.Navigation("CuadrosTarifarios");

                    b.Navigation("Envios");

                    b.Navigation("Liquidaciones");

                    b.Navigation("MotivosNoEntrega");

                    b.Navigation("ReglasOperativas");

                    b.Navigation("Repartidores");

                    b.Navigation("Rutas");

                    b.Navigation("SuscripcionesAvisos");

                    b.Navigation("Usuarios");

                    b.Navigation("Vehiculos");

                    b.Navigation("Zonas");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Operadores.Domain.Zona", b =>
                {
                    b.Navigation("FranjasHorarias");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Repartidor", b =>
                {
                    b.Navigation("Rutas");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Ruta", b =>
                {
                    b.Navigation("Incidencias");

                    b.Navigation("Paradas");

                    b.Navigation("Posiciones");

                    b.Navigation("Rendicion");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Rutas.Domain.Vehiculo", b =>
                {
                    b.Navigation("Rutas");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.CuadroTarifario", b =>
                {
                    b.Navigation("Envios");

                    b.Navigation("Tarifas");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.Liquidacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("LastMileUY.API.Modules.Tarifas.Domain.Tarifa", b =>
                {
                    b.Navigation("Ajustes");
                });
#pragma warning restore 612, 618
        }
    }
}
